import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportInvoicePDF = (invoice) => {
  const doc = new jsPDF();
  const primary = [26, 107, 92];

  // Header bar
  doc.setFillColor(...primary);
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PopEyez', 14, 12);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Event Management Platform', 14, 19);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 196, 12, { align: 'right' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.invoiceNumber || '', 196, 19, { align: 'right' });

  // Invoice meta
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  let y = 38;

  doc.setFont('helvetica', 'bold');
  doc.text('Vendor', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.vendor?.name || '—', 14, y + 6);
  doc.text(invoice.vendor?.email || '', 14, y + 12);

  doc.setFont('helvetica', 'bold');
  doc.text('Event', 100, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.event?.name || '—', 100, y + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Due Date', 160, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : '—', 160, y + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Status', 160, y + 14);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.status || '—', 160, y + 20);

  // Line items table
  y += 30;
  autoTable(doc, {
    startY: y,
    head: [['Description', 'Qty', 'Unit Price (EGP)', 'Total (EGP)']],
    body: (invoice.items || []).map(item => [
      item.description,
      item.quantity,
      (item.unitPrice || 0).toLocaleString(),
      (item.total || 0).toLocaleString(),
    ]),
    foot: [['', '', 'TOTAL', `EGP ${(invoice.totalAmount || 0).toLocaleString()}`]],
    headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [240, 240, 240], textColor: 40, fontStyle: 'bold' },
    styles: { fontSize: 10 },
    columnStyles: { 1: { halign: 'center' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
  });

  if (invoice.notes) {
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Notes:', 14, finalY);
    doc.setFont('helvetica', 'normal');
    doc.text(invoice.notes, 14, finalY + 6);
  }

  // Footer
  const pageH = doc.internal.pageSize.height;
  doc.setFillColor(...primary);
  doc.rect(0, pageH - 12, 210, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text('Generated by PopEyez Event Management Platform', 105, pageH - 4, { align: 'center' });

  doc.save(`${invoice.invoiceNumber || 'invoice'}.pdf`);
};

export const exportReportPDF = (report, eventName) => {
  const doc = new jsPDF();
  const primary = [26, 107, 92];

  // Header
  doc.setFillColor(...primary);
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('PopEyez', 14, 12);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Event Report', 14, 19);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(eventName || 'Event', 196, 18, { align: 'right' });

  doc.setTextColor(40, 40, 40);
  let y = 38;

  // Summary stats
  const stats = [
    ['Total Tasks', report.tasks?.total ?? '—'],
    ['Completed Tasks', report.tasks?.done ?? '—'],
    ['Total Guests', report.guests?.total ?? '—'],
    ['Checked In', report.guests?.checkedIn ?? '—'],
    ['Budget Spent (EGP)', (report.budget?.totalSpent ?? 0).toLocaleString()],
    ['Budget Total (EGP)', (report.budget?.totalBudget ?? 0).toLocaleString()],
  ];

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: stats,
    headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 11 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
  });

  // Task breakdown
  if (report.tasks) {
    y = doc.lastAutoTable.finalY + 14;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Task Breakdown', 14, y);
    autoTable(doc, {
      startY: y + 4,
      head: [['Status', 'Count']],
      body: [
        ['Not Assigned', report.tasks.notAssigned ?? 0],
        ['Pending', report.tasks.pending ?? 0],
        ['In Progress', report.tasks.inProgress ?? 0],
        ['Done', report.tasks.done ?? 0],
      ],
      headStyles: { fillColor: [80, 80, 80], textColor: 255 },
      styles: { fontSize: 10 },
    });
  }

  // Budget breakdown
  if (report.budget?.items?.length) {
    y = doc.lastAutoTable.finalY + 14;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Budget Items', 14, y);
    autoTable(doc, {
      startY: y + 4,
      head: [['Category', 'Description', 'Amount (EGP)']],
      body: report.budget.items.map(b => [b.category, b.description, (b.amount || 0).toLocaleString()]),
      headStyles: { fillColor: [80, 80, 80], textColor: 255 },
      styles: { fontSize: 10 },
      columnStyles: { 2: { halign: 'right' } },
    });
  }

  // Footer
  const pageH = doc.internal.pageSize.height;
  doc.setFillColor(...primary);
  doc.rect(0, pageH - 12, 210, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(`Generated by PopEyez · ${new Date().toLocaleDateString()}`, 105, pageH - 4, { align: 'center' });

  doc.save(`report-${eventName?.replace(/\s+/g, '-') || 'event'}.pdf`);
};
